set shell := ["bash", "-euo", "pipefail", "-c"]

check:
    go test -coverprofile=coverage.out ./...
    golangci-lint run ./...
    govulncheck ./...
    cd web/static/vendor/htmx && if command -v sha256sum >/dev/null 2>&1; then sha256sum --check SHA256SUMS; else shasum -a 256 --check SHA256SUMS; fi
